DROP TEXT SEARCH CONFIGURATION IF EXISTS public.polish;
DROP TEXT SEARCH DICTIONARY IF EXISTS polish_ispell;
DROP TEXT SEARCH DICTIONARY IF EXISTS polish_synonym;
DROP TEXT SEARCH DICTIONARY IF EXISTS polish_thesaurus;